### ISSUE TITLE
Error message with scvelo function 

### ISSUE THREAD

**Issue by zyb1984** [kevinrue/velociraptor#62]
Because of the timeout, the download of  miniconda was shut down during  with scvelo function process, and when I re-run the scvelo function, an error message was reported, with error information " Error in installConda() : conda installation failed with status code '2'", 
how to solve this problem?
   Or can the miniconda be installed through "reticulate", or maybe I can install the python dependency with another workflow?

**Comment by kevinrue** [comment]
Does the closed issue mean that you solved it?

If so, I would be grateful if you could briefly describe how you approached the issue. It could be useful to guide other users facing the same issue in the future.

I'm also not sure what caused the original issue, from the description above.
